### ISSUE TITLE
Example for adding data to ActionSubmit

### ISSUE THREAD

**Issue by wonboyn** [ku222/AdaptiveCardBuilder#3]
Hi there,

Can you provide an example of passing initial data key/value pairs to an ActionSubmit.

Thanks in advance

Tim

**Comment by ku222** [comment]
Hi Tim thanks for reaching out,
You can pass initial data to an Action Submit element in a similar fashion
to here (as a series of key-value pairs):
*https://adaptivecards.io/explorer/Action.Submit.html
<https://adaptivecards.io/explorer/Action.Submit.html>*

*def **make_example_card*() -> AdaptiveCard:
     card = *AdaptiveCard*()
     card.add([
          *TextBlock*(*text*="Please enter your name"),
          *InputText*(*id*="name_input", *placeholder*="Enter your name
here"),
          *ActionSubmit*(*title*="Click to submit your details", *data*={
"action": "details_submitted"})
     ])
     *return *card


*from* botbuilder.core *import *CardFactory
*from *botbuilder.schema *import *Attachment
*async def **send_example_card_from_within_dialog*(card: *AdaptiveCard*,
dc: *DialogContext*) -> None:
     # turn card into a dictionary object
     card_dict = *await *card.to_dict()
     # create an Attachment object from the card via Microsoft's CardFactory
     attachment: *Attachment *= *CardFactory*.adaptive_card(card_dict)
     # wrap attachment within an Activity object, send to user
     message: *Activity *= *Activity*(attachments=[attachment])
     *await *dc.context.send_activity(message)


When the user clicks on the submit button, the following data will be
submitted to your bot:
{
    "action": "details_submitted",
    "name_input": "<Text from InputText>"
}

From within the active dialog, you can access that user-submitted data via
the dialog & turn context objects like so - *DialogContext.*
*TurnContext.activity.value*. This will retrieve the same dictionary above.

I've found it helpful when prototyping complex cards to stick them in the
Visualiser tool and see how they turn out/function:
*https://adaptivecards.io/visualizer/
<https://adaptivecards.io/visualizer/>*

Hope that helps!

**Comment by wonboyn** [comment]
Thanks for the example & thanks for the module!
